# Generated by Django 4.0.4 on 2022-04-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
