# Generated by Django 4.0.4 on 2022-04-30 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orderhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 19, 16, 20, 241831)),
        ),
    ]
