# Generated by Django 4.0.4 on 2022-05-02 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orderhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 16, 40, 51, 827866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rewardpoint',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
